---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

workspace:
  path: /go/src/gitlab.digital.homeoffice.gov.uk/${DRONE_REPO}

steps:
- name: build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker login --username $${DOCKER_USERNAME} --password $${DOCKER_PASSWORD} quay.io/ukhomeofficedigital
  - docker build -t dq-piwik:$${DRONE_COMMIT_SHA} app --no-cache
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: push_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io/ukhomeofficedigital
  - docker tag dq-piwik:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dq-piwik:latest
  - docker tag dq-piwik:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dq-piwik:$${DRONE_COMMIT_SHA}
  - docker tag dq-piwik:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dq-piwik:$${DRONE_REPO_BRANCH}
  - docker push quay.io/ukhomeofficedigital/dq-piwik:latest
  - docker push quay.io/ukhomeofficedigital/dq-piwik:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/dq-piwik:$${DRONE_REPO_BRANCH}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: trivy_scan_jira-docker
  pull: if-not-exists
  image: aquasec/trivy
  commands:
  - trivy --ignore-unfixed --exit-code 1 --no-progress quay.io/ukhomeofficedigital/dq-piwik:$${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: deploy
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export KUBE_SERVER=$${KUBE_SERVER_DEV}
  - export KUBE_NAMESPACE=$${KUBE_NAMESPACE_DEV}
  - export KUBE_TOKEN=$${KUBE_TOKEN_DEV}
  - export PIWIK_SALT=$(echo -n $${PIWIK_SALT_DEV} | base64)
  - export PIWIK_DBNAME=$(echo -n $${PIWIK_DBNAME} | base64)
  - export PIWIK_MYSQL_DB_PREFIX=$${PIWIK_DB_PREFIX}
  - export PIWIK_APP_HOST=$${PIWIK_APP_HOST}
  - "cd kube_templated\nkd --file secret.yaml --file network-policy.yaml --file deployment.yaml --file service.yaml --file ingress.yaml\n"
  environment:
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE_DEV:
      from_secret: KUBE_NAMESPACE_DEV
    KUBE_SERVER_DEV:
      from_secret: KUBE_SERVER_DEV
    KUBE_TOKEN_DEV:
      from_secret: KUBE_TOKEN_DEV
    PIWIK_APP_HOST:
      from_secret: PIWIK_APP_HOST
    PIWIK_DBNAME:
      from_secret: PIWIK_DBNAME
    PIWIK_DB_PREFIX:
      from_secret: PIWIK_DB_PREFIX
    PIWIK_SALT_DEV:
      from_secret: PIWIK_SALT_DEV
  when:
    branch:
      exclude:
      - master
    event:
    - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
