pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-piwik
    secrets: [ docker_username, docker_password ]
    context: app
    dockerfile: app/Dockerfile
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_REPO_BRANCH}
    when:
      event: push


  deploy:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - INSECURE_SKIP_TLS_VERIFY=true
    secrets:
      - KUBE_SERVER_DEV
      - KUBE_NAMESPACE_DEV
      - KUBE_TOKEN_DEV
      - PIWIK_SALT_DEV
      - PIWIK_DBNAME
      - PIWIK_APP_HOST
    commands:
      - export KUBE_SERVER=$${KUBE_SERVER_DEV}
      - export KUBE_NAMESPACE=$${KUBE_NAMESPACE_DEV}
      - export KUBE_TOKEN=$${KUBE_TOKEN_DEV}
      - export PIWIK_SALT=$(echo -n $${PIWIK_SALT_DEV} | base64)
      - export PIWIK_DBNAME=$(echo -n $${PIWIK_DBNAME} | base64)
      - export PIWIK_DB_PREFIX=$(echo -n $${PIWIK_DB_PREFIX} | base64)
      - export PIWIK_APP_HOST=$${PIWIK_APP_HOST}
      - |
          cd kube_templated
          kd --file secret.yaml \
            --file network-policy.yaml \
            --file deployment.yaml \
            --file service.yaml \
            --file ingress.yaml
    when:
      event: [ push, deployment ]
      branch: master
