apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piwik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: piwik
    spec:
      containers:
        - name: piwik
          image: quay.io/ukhomeofficedigital/dq-piwik:{{.DRONE_COMMIT_SHA}}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
          ports:
          - name: http
            containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: PIWIK_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: piwik-rds-access
                  key: username
            - name: PIWIK_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: piwik-rds-access
                  key: password
            - name: PIWIK_MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: piwik-rds-access
                  key: endpoint
            - name: PIWIK_MYSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: piwik-rds-access
                  key: database_name
            - name: PIWIK_APP_SALT
              valueFrom:
                secretKeyRef:
                  name: piwik-secrets
                  key: salt
            - name: PIWIK_APP_HOST
              value: {{ .PIWIK_APP_HOST }}
