---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piwik-ingress
  annotations:
    ingress.kubernetes.io/secure-backends: "false"
    kubernetes.io/ingress.class: "nginx-external"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .PIWIK_APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: piwik
          servicePort: http
        path: /
  tls:
  - hosts:
    - {{ .PIWIK_APP_HOST }}
    - "www.{{ .PIWIK_APP_HOST }}"
