---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piwik-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - {{ .PIWIK_APP_HOST }}
    secretName: piwik-external-tls
  rules:
  - host: {{ .HOSTNAME}}
  - "www.{{ .PIWIK_APP_HOST }}"
    http:
      paths:
      - backend:
          serviceName: piwik
          servicePort: https
        path: /
