---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piwik-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .PIWIK_APP_HOST }}
    secretName: piwik-tls
  rules:
  - host: {{ .PIWIK_APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: piwik
          servicePort: 80
        path: /
