---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piwik-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/secure-backends: "false"
    ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  rules:
  - host: {{ .PIWIK_APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: piwik
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{ .PIWIK_APP_HOST }}
    - "www.{{ .PIWIK_APP_HOST }}"
    secretName: piwik-external-tls
