---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: piwik-ingress
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/ingress.class: "nginx-external"
  labels:
    stable.k8s.psg.io/kcm.class: default
spec:
  rules:
  - host: {{ .PIWIK_APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: piwik
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{ .PIWIK_APP_HOST }}
    - "www.{{ .PIWIK_APP_HOST }}"
    secretName: piwik-external-tls
