apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-piwik
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  podSelector:
    matchLabels:
      name: piwik
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
        - protocol: TCP
          port: 9000
