apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-piwik
spec:
  podSelector:
    matchLabels:
      name: piwik
  ingress:
    - ports:
      - protocol: TCP
        port: 80
